name: pd-multipool-cest
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.7.0=py39h06a4308_0
  - aom=3.6.0=h6a678d5_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h5eee18b_1
  - asttokens=3.0.0=py39h06a4308_0
  - async-lru=2.0.4=py39h06a4308_0
  - attrs=24.3.0=py39h06a4308_0
  - babel=2.16.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.13.4=py39h06a4308_0
  - blas=1.0=mkl
  - bleach=6.2.0=py39h06a4308_0
  - blosc=1.21.6=hf7d4471_0
  - brotli=1.0.9=h5eee18b_9
  - brotli-bin=1.0.9=h5eee18b_9
  - brotlicffi=1.0.9.2=py39h6a678d5_1
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.16.0=he5ede1b_6
  - certifi=2025.7.14=py39h06a4308_0
  - cffi=1.17.1=py39h1fdaa30_1
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py39h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.11=py39h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - giflib=5.2.2=h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - h11=0.16.0=py39h06a4308_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - httpcore=1.0.9=py39h06a4308_0
  - httpx=0.28.1=py39h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py39h06a4308_0
  - imagecodecs=2024.9.22=py39h652d938_1
  - imageio=2.37.0=py39h06a4308_0
  - importlib-metadata=8.5.0=py39h06a4308_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py39h06a4308_1
  - ipython=8.15.0=py39h06a4308_0
  - jedi=0.19.2=py39h06a4308_0
  - jinja2=3.1.6=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.25=py39h06a4308_0
  - jsonschema=4.25.0=py39h06a4308_0
  - jsonschema-specifications=2023.7.1=py39h06a4308_0
  - jupyter-lsp=2.2.5=py39h06a4308_0
  - jupyter_client=8.6.3=py39h06a4308_0
  - jupyter_core=5.8.1=py39h06a4308_0
  - jupyter_events=0.12.0=py39h06a4308_0
  - jupyter_server=2.16.0=py39h06a4308_0
  - jupyter_server_terminals=0.5.3=py39h06a4308_0
  - jupyterlab=4.4.4=py39h06a4308_0
  - jupyterlab_pygments=0.3.0=py39h06a4308_0
  - jupyterlab_server=2.27.3=py39h06a4308_0
  - jxrlib=1.1=h7b6447c_2
  - krb5=1.21.3=h8a1dbc1_1
  - lazy_loader=0.4=py39h06a4308_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libaec=1.1.3=h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcurl=8.14.1=h31d0fb7_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzopfli=1.0.3=he6710b0_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py39h5eee18b_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mistune=3.1.2=py39h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_2
  - mkl_fft=1.3.11=py39h5eee18b_0
  - mkl_random=1.2.8=py39h1128e8f_0
  - narwhals=1.31.0=py39h06a4308_1
  - nbclient=0.10.2=py39h06a4308_0
  - nbconvert-core=7.16.6=py39h06a4308_0
  - nbformat=5.10.4=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py39h06a4308_0
  - networkx=3.2.1=py39h06a4308_0
  - notebook=7.4.4=py39h06a4308_0
  - notebook-shim=0.2.4=py39h06a4308_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.17=h5eee18b_0
  - overrides=7.4.0=py39h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py39h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=py39h06a4308_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.3.0=py39hb1c3d2d_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=4.3.7=py39h06a4308_0
  - plotly=6.0.1=py39he3bba80_0
  - prometheus_client=0.21.1=py39h06a4308_0
  - prompt-toolkit=3.0.43=py39h06a4308_0
  - psutil=5.9.0=py39h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.23=he99959a_0
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-fastjsonschema=2.20.0=py39h06a4308_0
  - python-json-logger=3.2.1=py39h06a4308_0
  - pyyaml=6.0.2=py39h5eee18b_0
  - pyzmq=26.2.0=py39h6a678d5_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py39h06a4308_0
  - requests=2.32.4=py39h06a4308_0
  - rfc3339-validator=0.1.4=py39h06a4308_0
  - rfc3986-validator=0.1.1=py39h06a4308_0
  - rpds-py=0.22.3=py39h4aa5aa6_0
  - scikit-image=0.24.0=py39h1128e8f_0
  - scipy=1.13.1=py39h5f9d8c6_1
  - send2trash=1.8.2=py39h06a4308_1
  - six=1.17.0=py39h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py39h06a4308_0
  - soupsieve=2.5=py39h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tbb-devel=2021.8.0=hdb19cb5_0
  - terminado=0.17.1=py39h06a4308_0
  - tinycss2=1.4.0=py39h06a4308_0
  - tk=8.6.14=h993c535_1
  - tomli=2.0.1=py39h06a4308_0
  - tornado=6.5.1=py39h5eee18b_0
  - traitlets=5.14.3=py39h06a4308_0
  - typing-extensions=4.12.2=py39h06a4308_0
  - typing_extensions=4.12.2=py39h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py39h06a4308_0
  - wcwidth=0.2.13=py39h06a4308_0
  - webencodings=0.5.1=py39h06a4308_1
  - websocket-client=1.8.0=py39h06a4308_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zfp=1.0.0=h6a678d5_0
  - zipp=3.21.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zlib-ng=2.0.7=h5eee18b_0
  - zstd=1.5.6=hc292b87_0
  - pip:
      - cmcrameri==1.9
      - contourpy==1.3.0
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.59.0
      - fsspec==2024.6.1
      - importlib-resources==6.5.2
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - numpy==2.0.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pip==24.3.1
      - pyparsing==3.2.3
      - setuptools==44.1.1
      - sympy==1.13.3
      - tifffile==2024.8.30
      - torch==2.7.1+cu118
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - triton==3.3.1
prefix: /home/hagar/anaconda3/envs/pd-multipool-cest
